In [1]:
import numpy as np

In [2]:
#list dari python 
list_a = [1,2,3,4,5]
list_a

[1, 2, 3, 4, 5]

In [3]:
#numpy array
array_b = np.array([6,7,8,9,10])
array_b

array([ 6,  7,  8,  9, 10])

In [4]:
for i in range(len(list_a)):
    list_a[i] += 10
list_a

[11, 12, 13, 14, 15]

In [5]:
array_b += 10 #gunakan = untuk mengubah data
array_b

array([16, 17, 18, 19, 20])

In [6]:
array_b *= 7
array_b

array([112, 119, 126, 133, 140])

In [7]:
array_b + 10 #tidak mengubah value sebenernya 

array([122, 129, 136, 143, 150])

In [8]:
array_b

array([112, 119, 126, 133, 140])

In [9]:
#penjumlahan list
list_a = [1, 2, 3, 4, 5]
list_b = [10, 20, 30, 40, 50]

list_c = []
for i in range(len(list_a)): #range untuk membuat perulangan dari 0 s/d n-1
    list_c.append(list_a[i]+list_b[i]) #.append menambahkan nilai pada list_c
list_c
    

[11, 22, 33, 44, 55]

In [10]:
#penjumlahan array
array_a = np.array([1,2,3,4,5])
array_b = np.array([10,20,30,40,50])

array_c = array_a + array_b
array_c

array([11, 22, 33, 44, 55])

In [12]:
#array 1 dimensi
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
#array 2 dimensi 
b = np.array([[1,2,3,4],
              [5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
#jumlah dimensi
b.ndim

2

In [17]:
#ukuran masing-masing dimensi
b.shape

(2, 4)

In [18]:
c = np.array([1,2,3,4,5,6,7,8])
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
c = np.append(c,9) #menambahkan angka 9 di belakang 
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
c = np.append(0,c) #menambahkan angka 0 di depan
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#slicing 1 dimensi
d = np.array([1,2,3,4,5,6,7,8,9,10])

In [25]:
d[2:5]

array([3, 4, 5])

In [26]:
d[:5]

array([1, 2, 3, 4, 5])

In [27]:
d[5:]

array([ 6,  7,  8,  9, 10])

In [28]:
d[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#slicing 2 dimensi
e = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
#slicing baris 0:2
#slicing kolom 1:4

e[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [33]:
e[0:2, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
e[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

In [35]:
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
e.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [37]:
e.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [39]:
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
e.ravel() #mengubah dimensi apapun menjadi 1 dimensi atau di sebut sebagai flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
#aritmatika
e * 7

array([[  7,  14,  21,  28,  35],
       [ 42,  49,  56,  63,  70],
       [ 77,  84,  91,  98, 105]])

In [44]:
f = np.array([[11,12,13,14,15],[8,9,10,11,12],[9,8,7,6,5]])
f

array([[11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12],
       [ 9,  8,  7,  6,  5]])

In [45]:
e * f

array([[ 11,  24,  39,  56,  75],
       [ 48,  63,  80,  99, 120],
       [ 99,  96,  91,  84,  75]])

In [48]:
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [47]:
e.mean()

8.0

In [49]:
e.mean(axis=0)

array([ 6.,  7.,  8.,  9., 10.])